server:
  port: 80
spring:
  application:
    name: payment-consumer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
feign:
  hystrix:
    # 在feign中开启Hystrix
    enabled: true